# Generated by Django 6.0.5 on 2026-05-08 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('keywords', models.TextField(help_text='収集キーワード（スペース区切りまたはOR/AND）')),
                ('language', models.CharField(choices=[('ja', '日本語'), ('en', '英語'), ('both', '両方')], default='both', max_length=10)),
                ('frequency', models.CharField(choices=[('daily', '毎日'), ('weekly', '毎週')], default='daily', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_collected_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('title_ja', models.CharField(blank=True, max_length=500)),
                ('url', models.URLField(max_length=2000)),
                ('source', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('domestic', '国内'), ('international', '海外')], max_length=20)),
                ('published_at', models.DateTimeField()),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='collector.theme')),
            ],
            options={
                'ordering': ['-published_at'],
                'constraints': [models.UniqueConstraint(fields=('theme', 'url'), name='unique_article_per_theme')],
            },
        ),
    ]
