# Generated by Django 6.0.5 on 2026-05-11 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='status',
            field=models.CharField(choices=[('idle', '待機中'), ('collecting', '収集中')], default='idle', max_length=15),
        ),
    ]
