# Generated by Django 6.0.5 on 2026-05-11 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_theme_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='rss_feeds',
            field=models.TextField(blank=True, default='', help_text='1行1URLでRSSフィードを追加（任意）'),
        ),
    ]
