# Generated by Django 6.0.5 on 2026-05-11 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_theme_rss_feeds'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
