# Generated by Django 6.0.5 on 2026-05-08 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collector', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_type', models.CharField(choices=[('slack', 'Slack'), ('teams', 'Microsoft Teams')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('webhook_url', models.URLField(max_length=2000)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThemeChannelLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_links', to='notifications.notificationchannel')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_links', to='collector.theme')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('theme', 'channel'), name='unique_theme_channel')],
            },
        ),
    ]
